site_name: Saude Coletiva
copyright: 2023 Luiza H. Moretti
repo_name: RESUMOS
repo_url: https://luhm.github.io/saude_coletiva/

theme:
  name: material
#  icon:
#    logo: material/library-house
  features:
    - content.code.annotate
    - content.code.copy
 
  favicon: assets/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
   - attr_list
   - pymdownx.caret
   - pymdownx.mark
   - pymdownx.tilde
   - footnotes
   - pymdownx.smartsymbols
   - pymdownx.tasklist:
      clickable_checkbox: true

nav:
  - Saude Coletiva:
    - Informações Gerais: saude_coletiva/m4d3_saude_coletiva.md
    - Conteúdo:
      - Unidade 1: saude_coletiva/sc_conteudo1.md
      - Unidade 2: saude_coletiva/sc_conteudo2.md
      - Unidade 3: saude_coletiva/sc_conteudo3.md
      - Unidade 4: saude_coletiva/sc_conteudo4.md
    - Avaliações: saude_coletiva/sc_avaliacoes.md


