#!/bin/bash

sudo apt-get update

sudo apt-get install software-properties-common apt-transport-https ca-certificates curl pandoc --fix-missing -y

curl -fSsL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-edge.gpg >/dev/null

echo 'deb [signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main' | tee /etc/apt/sources.list.d/microsoft-edge.list

sudo apt-get update && sudo apt-get install microsoft-edge-stable -y
